name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Import GPG private key
        id: import-gpg-key
        run: |
          echo "${{ secrets.RELEASE_PRIVATE_PGP }}" | base64 --decode | gpg --import --batch --yes 2>&1 | tee /dev/tty | grep -oP 'key\s+\K\w+' > .github/gpg-key-id.txt

      - name: Read GPG key ID
        id: read-gpg-key-id
        run: |
          GPG_KEY_ID=$(cat .github/gpg-key-id.txt)
          echo "gpg-key-id=$GPG_KEY_ID" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ steps.read-gpg-key-id.outputs.gpg-key-id }}
        run: npx semantic-release
