name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Import GPG private key
        run: |
          echo "${{ secrets.RELEASE_PRIVATE_PGP }}" | base64 --decode | gpg --import --batch --yes

      - name: Set GPG passphrase
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --passphrase-fd 0 --pinentry-mode loopback -s

      - name: Install dependencies
        run: npm install semantic-release semantic-release-git @semantic-release/changelog @semantic-release/exec

      - name: Generate .releaserc.js
        run: |
          echo "const config = {
            branches: ['main'],
            plugins: [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              '@semantic-release/changelog',
              ['@semantic-release/npm', {
                npmPublish: false
              }],
              ['@semantic-release/git', {
                assets: ['package.json', 'package-lock.json'],
                message: 'chore(release): \${nextRelease.version} [skip ci]\\n\\n\${nextRelease.notes}'
              }],
              ['@semantic-release/exec', {
                prepareCmd: 'echo Prepare step',
                publishCmd: 'echo Publish step'
              }]
            ]
          };

          module.exports = config;
          " > .releaserc.js

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
