name: Remove Labels
on:
  workflow_call:
    inputs:
      labels:
        description: 'Comma-separated list of labels to remove'
        type: string
        required: true
jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Labels
        run: |
          # Remove labels
          for label in $(echo "${{ inputs.labels }}" | tr ',' '\n'); do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "${{ github.event.pull_request.issues.href }}/labels/${label}"
          done

