on:
  workflow_call:
    inputs:
      status-name:
        description: 'A name of the status to use'
        default: 'CI'
        required: false
        type: string
      name:
        description: 'Name to greet'
        required: false
        type: string
      
jobs:
  notify_contributor_and_label_required:
    secrets: inherit
    uses: ./.github/workflows/post-usage.yml

  start-pipeline:
    needs: [notify_contributor_and_label_required]
    # Only start if the issue contains the lable ok-to-test and the run pipeline was posted by a collaborator
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/run pipeline' && github.event.comment.author_association=='CONTRIBUTOR' && contains(github.event.issue.labels.*.name, 'ok-to-test') }}
    uses: ./.github/workflows/get-latest-commit-id.yml
    with:
      github_token: ${{ github.token }}
          
  set-commit-status-running:
    uses: ./.github/workflows/set-commit-status.yml
    needs: [start-pipeline]
    with:
      github_token: ${{ github.token }}
      state: "pending"
      description: "Running"
      context: ${{ inputs.status-name }}
      sha: ${{needs.start-pipeline.outputs.commit_id}}
      target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      github_repository: ${{ github.repository }}

  execute-main-workflow:
    needs: [start-pipeline, set-commit-status-running]
    uses: ./.github/workflows/sample.yml
    secrets: ${{ toJson(secrets) }}
    with:
      name: ${{ inputs.name }}
      checkout_commit: ${{needs.start-pipeline.outputs.commit_id}}
      GITHUB_BASE_REF: ${{ needs.start-pipeline.outputs.target_branch}}
      GITHUB_HEAD_REF: ${{ needs.start-pipeline.outputs.source_branch}}
      secrets: ${{ inputs.secrets }}

  set-commit-status-success:
      needs: [start-pipeline, execute-main-workflow]
      if: ${{ success() }}
      uses: ./.github/workflows/set-commit-status.yml
      with:
        github_token: ${{ github.token }}
        state: "success"
        description: "Complete - Success"
        context: ${{ inputs.status-name }}
        sha: ${{ needs.start-pipeline.outputs.commit_id }}
        target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        github_repository: ${{ github.repository }}

  set-commit-status-failure:
    needs: [start-pipeline, execute-main-workflow]
    if: ${{ failure() }}
    uses: ./.github/workflows/set-commit-status.yml
    with:
      github_token: ${{ github.token }}
      state: "failure"
      description: "Complete - Failure"
      context: ${{ inputs.status-name }}
      sha: ${{ needs.start-pipeline.outputs.commit_id }}
      target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      github_repository: ${{ github.repository }}

