on:
  workflow_call:
    inputs:
      status-name:
        description: 'A name of the status to use'
        default: 'CI'
        required: false
        type: string
      workflow-version:
        description: 'Workflow version to use'
        default: 'main'
        required: false
        type: string

jobs:
  start-pipeline:
    name: Get Commit ID
    runs-on: ubuntu-latest
    outputs:
      commit_id:  ${{ steps.commit_id.outputs.COMMIT_ID }}
    steps:
      - name: Get Latest Commit ID
        id: commit_id
        run: |
          pull_request_url=$(jq -r ".issue.pull_request.url" "$GITHUB_EVENT_PATH")
          commit_id=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "$pull_request_url" \
            | jq -r ".head.sha")
          echo "COMMIT_ID=$commit_id" >> "$GITHUB_OUTPUT"
      - name: Print Latest Commit ID
        run: |
          echo "Latest commit ID is ${{ env.COMMIT_ID }}"
          echo "URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Input: ${{ inputs.status-name }}"
          echo "${{ toJson(github) }}"
          echo "context: ${{ inputs.status-name }}"

  set-commit-status-running:
    uses: daniel-test-bed/workflows/.github/workflows/set-commit-status.yml@main
    needs: [start-pipeline]
    with:
      github_token: ${{ github.token }}
      state: "pending"
      description: "Running"
      context: ${{ inputs.status-name }}
      sha: ${{needs.start-pipeline.outputs.commit_id}}
      target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      github_repository: ${{ github.repository }}

  execute-main-workflow:
    needs: [set-commit-status-running]
    uses: "daniel-test-bed/workflows/.github/workflows/sample.yml@${{inputs.workflow-version}}"

  set-commit-status-success:
      needs: [start-pipeline, execute-main-workflow]
      if: ${{ success() }}
      uses: daniel-test-bed/workflows/.github/workflows/set-commit-status.yml@main
      with:
        github_token: ${{ github.token }}
        state: "success"
        description: "Complete - Success"
        context: ${{ inputs.status-name }}
        sha: ${{ needs.start-pipeline.outputs.commit_id }}
        target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        github_repository: ${{ github.repository }}

  set-commit-status-failure:
    needs: [start-pipeline, execute-main-workflow]
    if: ${{ failure() }}
    uses: daniel-test-bed/workflows/.github/workflows/set-commit-status.yml@main
    with:
      github_token: ${{ github.token }}
      state: "failure"
      description: "Complete - Failure"
      context: ${{ inputs.status-name }}
      sha: ${{ needs.start-pipeline.outputs.commit_id }}
      target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      github_repository: ${{ github.repository }}

