on:
  workflow_call:
    inputs:
        status-name:
          description: 'A name of the status to use'
          default: 'CI'
          required: false
          type: string

jobs:    
  start-pipeline:
    name: Get Commit ID
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Commit ID
        id: commit_id
        run: |
          pull_request_url=$(jq -r ".issue.pull_request.url" "$GITHUB_EVENT_PATH")
          commit_id=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
            "$pull_request_url" \
            | jq -r ".head.sha")
          echo "COMMIT_ID=$commit_id" >> $GITHUB_ENV
      - name: Print Latest Commit ID
        run: |
          echo "Latest commit ID is ${{ env.COMMIT_ID }}"
          echo "URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Input: ${{ inputs.status-name }}"
          echo "${{ toJson(github) }}"
  set-commit-status-running:
    uses:  daniel-test-bed/workflows/.github/workflows/set-commit-status.yml@main
    needs: [start-pipeline] 
    with:
      github_token: ${{ github.token }}
      state: "Pending"
      description: "Running"
      context: ${{ github.event.inputs.status-name }}
      sha: ${{ needs.start-pipeline.outputs.COMMIT_ID }}
      target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
  execute-main-workflow:
    uses: daniel-test-bed/workflows/.github/workflows/sample.yml@main
  
  set-commit-status-complete:
    uses:  daniel-test-bed/workflows/.github/workflows/set-commit-status.yml@main
    needs: [start-pipeline, execute-main-workflow] 
    with:
      github_token: ${{ github.token }}
      state: ${{ steps.execute-main-workflow.outcomes.job.result }} == 'success' ?'success':'failure'
      description: "Complete"
      context: ${{ github.event.inputs.status-name }}
      sha: ${{ needs.start-pipeline.outputs.COMMIT_ID }}
      target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
